name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 0.1.9+4
homepage: https://github.com/LuisThein
repository: https://github.com/LuisThein/platform_maps_flutter
issue_tracker: https://github.com/LuisThein/platform_maps_flutter/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1

  apple_maps_flutter: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
